### ISSUE TITLE
modalview class doesn't get removed

### ISSUE THREAD

**Issue by freakyleaf** [jachinte/jquery.secretnav#1]
Upon clicking the 'transformed' page to bring it back to its original position, the modalview class doesn't get removed. This is evident in your two demos.

This presents a problem where the page's content flows out of the viewport, as the scrollbars never return, which is why it's not a problem in your demos.

**Comment by jachinte** [comment]
Hello @freakyleaf, thanks for notifying me about this error. I'll start working on solving it as soon as I can.

**Comment by jachinte** [comment]
The previous solution introduced another unwanted behavior. I'm working on it.

**Comment by freakyleaf** [comment]
Works great! :)
